# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample_20170503' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample_20170503
  
  pod 'SwiftGifOrigin', '~> 1.5'

  target 'sample_20170503Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample_20170503UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
