# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lunch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lunch
  pod 'SwiftGifOrigin', '~> 1.5'

  target 'lunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lunchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end